apiVersion: v1
kind: Service
metadata:
  name: {{ include "indopacom-merge.fullname" . }}
  labels:
    {{- include "indopacom-merge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portWeb }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.portApi }}
    - port: {{ .Values.service.portApi }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
  selector:
    {{- include "indopacom-merge.selectorLabels" . | nindent 4 }}
